[SlateEditor] Clean uui editor deps
epam/UUI pull request #1465
Opened 2023-07-05 14:15 UTC by dimaanj

## Summary 

Clean ui-editor dependencies

2023-07-10 16:03 UTC, AlekseyManetov requested changes

2023-07-10 16:03 UTC, AlekseyManetov commented on uui-editor/src/utils/onClickToolbarButton.ts
> +export const onClickToolbarButton = (editor: PlateEditor, key: string) => () => {
let's use more specific name, e.g.: handleMarkButtonClick

2023-07-19 11:40 UTC, dimaanj commented on uui-editor/src/components.tsx
> +        [ELEMENT_H1]: withProps(StyledElement, {
Fixed.

2023-07-19 11:40 UTC, dimaanj commented on uui-editor/src/utils/onClickToolbarButton.ts
> +export const onClickToolbarButton = (editor: PlateEditor, key: string) => () => {
Updated.

2023-07-25 15:47 UTC, merged