[Themes]: Update RTE
epam/UUI pull request #1703
Opened 2023-10-23 15:19 UTC by siarhei-epam

Add variables to RTE, remove SkinContext from UuiContexts, add neutral color to Button in uui package, move RichTextView, VirtualList, ScrollBars, Checkbox from skins to uui package, reverse neutral colors for "loveship dark" theme, update demos & examples

2023-10-23 17:38 UTC, AlekseyManetov requested changes

2023-10-23 17:38 UTC, AlekseyManetov commented on uui-editor/src/implementation/ColorBar.tsx
> +        <FlexRow rawProps={ { style: { border: '1px solid var(--uui-divider-light)' } } }>
let's move it to the css class

2023-10-23 17:38 UTC, AlekseyManetov commented on uui-editor/src/implementation/HeaderBar.tsx
> +            <FlexRow rawProps={ { style: { border: '1px solid var(--uui-divider-light)' } } }>
let's move it to the css class

2023-10-23 17:38 UTC, AlekseyManetov commented on uui-editor/src/implementation/NoteBar.tsx
> +        <FlexRow rawProps={ { style: { border: '1px solid var(--uui-divider-light)' } } }>
let's move it to the css class

2023-10-23 17:38 UTC, AlekseyManetov commented on uui-editor/src/plugins/tablePlugin/TableCell.module.scss
> +    border-bottom: 1px solid var(--uui-control-border);
May be better to use here table variables?

2023-10-24 08:25 UTC, vik753 approved these changes

2023-10-26 15:56 UTC, AlekseyManetov requested changes

2023-10-26 15:56 UTC, AlekseyManetov commented on app/src/docs/_examples/mainMenu/Responsive.example.tsx
> +import {
Fix imports layout

2023-10-27 12:24 UTC, AlekseyManetov requested changes

2023-10-27 12:24 UTC, AlekseyManetov commented on uui-editor/src/SlateEditor.tsx
> +                    <ScrollBars style={ { width: '100%' } }>
move to the css

2023-10-27 13:16 UTC, merged