[Feature]: ButtonBase rework
epam/UUI pull request #1935
Opened 2024-01-18 23:39 UTC by siarhei-epam

Class ButtonBase reworked to Clickable component function, all nesting components reworked, removed redundant props from nesting components, reworked Dropdown types

2024-01-19 09:39 UTC, vik753 approved these changes

2024-01-19 14:32 UTC, AlekseyManetov requested changes

2024-01-19 14:32 UTC, AlekseyManetov commented on uui/components/filters/FilterPanelItemToggler.tsx
> +    ref?: React.Ref<any>;
can we extend here from IDropdownTogglerProps and don't copy/past these properties? The same for IBasicPickerToggler

2024-01-19 14:32 UTC, AlekseyManetov commented on uui/components/widgets/Badge.tsx
> +                    key="icon-left"
do we still need key props here?

2024-01-21 21:47 UTC, siarhei-epam commented on uui-components/src/widgets/Clickable.tsx
> +        return React.createElement('a', {
We can't use JSX, because of union types.

2024-01-21 22:00 UTC, siarhei-epam commented on uui/components/buttons/Button.tsx
> +export type ButtonCoreProps = uuiComponents.ButtonProps;
We can't use interfaces for discriminated unions.
![image](https://github.com/epam/UUI/assets/97472156/ef5866b7-49fb-4113-ad6b-4c1f2a59827e)

2024-01-21 22:04 UTC, siarhei-epam commented on uui/components/buttons/Button.tsx
> +export type ButtonProps = ButtonMods & ButtonCoreProps;
We can't use interfaces with discriminated unions.
![image](https://github.com/epam/UUI/assets/97472156/b043edd1-93cd-4a59-b886-8343863e062c)

2024-01-22 16:35 UTC, AlekseyManetov requested changes

2024-01-22 16:35 UTC, AlekseyManetov commented on uui-core/src/types/pickers.ts
> +
Replace props below with inheritance from IDropdownTogglerProps

2024-01-22 16:54 UTC, merged

2024-02-12 09:53 UTC, NatalliaAlieva commented
Released in 5.6.0 ver.