Feature: sizes customizing - set of new components
epam/UUI pull request #2396
Opened 2024-06-28 16:02 UTC by siarhei-epam

### Description:
Added a set of new components with support for size customization

2024-08-29 16:15 UTC, AlekseyManetov requested changes

2024-08-29 16:15 UTC, AlekseyManetov commented on uui/settings.ts
> +                editable: '0',
hardcode editable value

2024-08-29 16:15 UTC, AlekseyManetov commented on uui/settings.ts
> +                utmost: '24',
Probably firstColumnPadding and lastColumnPading

2024-09-02 14:42 UTC, siarhei-epam commented on epam-promo/components/typography/Text.tsx
> +    size?: TextSize;
to be able to override the size type in the uui package, accordingly, this must be written in the skins

2024-09-02 15:36 UTC, siarhei-epam commented on uui/components/pickers/DataPickerBody.module.scss
> +:global(.uui-picker_input-body) {
we didn't use camel case, I brought to the unity of using classes on the project

2024-09-02 15:52 UTC, siarhei-epam commented on uui/components/tables/DataTable.tsx
> -    headerSize?: '36' | '48' | '60';
moved to DataTableMods to be able to override the type

2024-09-11 14:06 UTC, AlekseyManetov requested changes

2024-09-11 14:06 UTC, AlekseyManetov commented on uui/components/tables/DataTableHeaderCell.tsx
> +                        lineHeight={ settings.sizes.dataTable.header.row.cell.columnCaption.lineHeight as TextProps['lineHeight'] }
Probably we can move `settings.sizes.dataTable.header.row.cell.columnCaption.lineHeight` from settings to css variable?

2024-09-11 19:37 UTC, siarhei-epam commented on uui/components/pickers/PickerItem.tsx
> +                rawProps={ { style: { '--uui-picker_item-vertical-padding': `${settings.sizes.pickerInput.body.dropdown.row.cell.item.verticalPadding[itemSize]}px` } as React.CSSProperties } }
Here we need to dive a little deeper into this, collect the components and see how we can generalize

2024-09-13 10:12 UTC, merged

2024-09-25 11:41 UTC, NatalliaAlieva commented
Column header no longer wraps to 2 lines in the "Condensed view" example.
![Uploading Screenshot 2024-09-25 at 13.28.27.png…]()

2024-09-25 13:08 UTC, NatalliaAlieva commented
Navigation-chevron_right icon larger on Dev than on Prod.
<img width="353" alt="Screenshot 2024-09-25 at 15 02 18" src="https://github.com/user-attachments/assets/028188ef-ab3f-4e13-af45-ccb43ea6e720">