[HierarchicalListExample]: Custom hierarchical list example.
epam/UUI pull request #2460
Opened 2024-08-09 16:04 UTC by Kuznietsov

### Summary

In progress...

2024-09-02 15:54 UTC, AlekseyManetov requested changes

2024-09-02 15:54 UTC, AlekseyManetov commented on app/src/docs/_examples/dataSources/CustomHierarchicalList.example.tsx
> +                                    style={ { fill: 'var(--uui-icon)' } }
let's move it to the css class

2024-09-02 15:54 UTC, AlekseyManetov commented on app/src/docs/_examples/dataSources/CustomHierarchicalList.example.tsx
Let's move inline styles into css classes to make example more pure and readable

2024-09-02 15:54 UTC, AlekseyManetov commented on app/src/docs/_examples/dataSources/CustomHierarchicalList.example.tsx
> +            return 12 + (row.indent - 1) * 24;
If 12 it's a global padding for all items, let's set it via css and exclude from this calculation

2024-09-03 07:26 UTC, Kuznietsov commented on app/src/docs/_examples/dataSources/CustomHierarchicalList.example.tsx
> +                                    style={ { fill: 'var(--uui-icon)' } }
Done.

2024-09-03 09:31 UTC, merged

2024-09-13 07:37 UTC, NatalliaAlieva commented
Released in 5.9.2 ver.