[DatePicker][RangeDatePicker]: added ability to enter date in format different than props.format #806 and #828
epam/UUI pull request #832
Opened 2022-11-21 15:52 UTC by Sushasgit

Info ℹ️ 
https://github.com/epam/UUI/issues/806
https://github.com/epam/UUI/issues/828

2022-11-22 12:22 UTC, AlekseyManetov requested changes

2022-11-22 12:22 UTC, AlekseyManetov commented on uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx
> +        this.handleValueChange(value.selectedDate);
add  set selectedDate(check null value)

2022-11-22 12:22 UTC, AlekseyManetov commented on uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx
> +        const newValue = {
revert (?)

2022-11-23 16:06 UTC, Sushasgit commented on uui-components/src/inputs/DatePicker/BaseDatePicker.tsx
> +        if (this.state.inputValue && this.getIsValidDate(this.state.inputValue)) {
Thanks, done

2022-11-23 16:06 UTC, Sushasgit commented on uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx
> +        const newValue = {
Thanks, reverted

2022-11-24 12:15 UTC, AlekseyManetov requested changes

2022-11-24 13:26 UTC, Sushasgit commented on uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx
> +        if (dayjs(value, supportedDateFormats, true).isValid()) {
Thanks, done

2022-11-24 14:08 UTC, merged