Feature/figma tokens ihor UuiRangeDatePicker
epam/UUI pull request #870
Opened 2022-12-09 13:31 UTC by vik753

2022-12-22 13:29 UTC, vik753 commented on epam-promo/components/datePickers/index.ts
> -export * from './RangeDatePickerBody';
They imports from uui

2022-12-22 13:29 UTC, vik753 commented on loveship/components/datePickers/index.ts
> -export * from './DatePickerBody';
They imports from uui

2023-01-04 13:30 UTC, vik753 commented on epam-promo/components/datePickers/docs/RangeDatePicker.doc.scss
> +    background-color: var(--uui-rdtp-bg-color);
done

2023-01-04 13:37 UTC, vik753 commented on uui/components/datePickers/RangeDatePicker.tsx
> +                    cx={ cx(this.props.bodyCx, 'date-range-picker-vars', css.dateInput, css['size-' + (this.props.size || 36)], this.state.inFocus === 'from' && uuiMod.focus) }
done

2023-01-04 16:21 UTC, AlekseyManetov requested changes

2023-01-04 16:21 UTC, AlekseyManetov commented on epam-promo/components/filters/FilterRangeDatePickerBody.tsx
> +import css from "@epam/uui/components/datePickers/RangeDatePicker.scss";
create separate styles file inside promo

2023-01-04 16:21 UTC, AlekseyManetov commented on uui/components/datePickers/DatePicker.tsx
> +export interface UuiDatePickerProps extends DatePickerCoreProps, SizeMod, IHasEditMode {}
rename to DatePickerProps

2023-01-06 13:05 UTC, merged